#!groovy

// Generated by IBM TransformationAdvisor
// Sun Sep 15 16:49:35 GMT 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}